// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _config_encoder_HH_
#define _config_encoder_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct config_encoder : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > enc_ctrl_V_V_TDATA;
    sc_out< sc_logic > enc_ctrl_V_V_TVALID;
    sc_in< sc_logic > enc_ctrl_V_V_TREADY;
    sc_out< sc_lv<8> > din_words_TDATA;
    sc_out< sc_logic > din_words_TVALID;
    sc_in< sc_logic > din_words_TREADY;
    sc_out< sc_lv<1> > din_words_TLAST;
    sc_out< sc_lv<8> > dout_words_TDATA;
    sc_out< sc_logic > dout_words_TVALID;
    sc_in< sc_logic > dout_words_TREADY;
    sc_out< sc_lv<1> > dout_words_TLAST;


    // Module declarations
    config_encoder(sc_module_name name);
    SC_HAS_PROCESS(config_encoder);

    ~config_encoder();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > enc_ctrl_V_V_1_data_out;
    sc_signal< sc_logic > enc_ctrl_V_V_1_vld_in;
    sc_signal< sc_logic > enc_ctrl_V_V_1_vld_out;
    sc_signal< sc_logic > enc_ctrl_V_V_1_ack_in;
    sc_signal< sc_logic > enc_ctrl_V_V_1_ack_out;
    sc_signal< sc_lv<32> > enc_ctrl_V_V_1_payload_A;
    sc_signal< sc_lv<32> > enc_ctrl_V_V_1_payload_B;
    sc_signal< sc_logic > enc_ctrl_V_V_1_sel_rd;
    sc_signal< sc_logic > enc_ctrl_V_V_1_sel_wr;
    sc_signal< sc_logic > enc_ctrl_V_V_1_sel;
    sc_signal< sc_logic > enc_ctrl_V_V_1_load_A;
    sc_signal< sc_logic > enc_ctrl_V_V_1_load_B;
    sc_signal< sc_lv<2> > enc_ctrl_V_V_1_state;
    sc_signal< sc_logic > enc_ctrl_V_V_1_state_cmp_full;
    sc_signal< sc_lv<8> > din_words_V_data_V_1_data_out;
    sc_signal< sc_logic > din_words_V_data_V_1_vld_in;
    sc_signal< sc_logic > din_words_V_data_V_1_vld_out;
    sc_signal< sc_logic > din_words_V_data_V_1_ack_in;
    sc_signal< sc_logic > din_words_V_data_V_1_ack_out;
    sc_signal< sc_logic > din_words_V_data_V_1_sel_rd;
    sc_signal< sc_logic > din_words_V_data_V_1_sel;
    sc_signal< sc_lv<2> > din_words_V_data_V_1_state;
    sc_signal< sc_lv<1> > din_words_V_last_V_1_data_out;
    sc_signal< sc_logic > din_words_V_last_V_1_vld_in;
    sc_signal< sc_logic > din_words_V_last_V_1_vld_out;
    sc_signal< sc_logic > din_words_V_last_V_1_ack_in;
    sc_signal< sc_logic > din_words_V_last_V_1_ack_out;
    sc_signal< sc_logic > din_words_V_last_V_1_sel_rd;
    sc_signal< sc_logic > din_words_V_last_V_1_sel;
    sc_signal< sc_lv<2> > din_words_V_last_V_1_state;
    sc_signal< sc_lv<8> > dout_words_V_data_V_1_data_out;
    sc_signal< sc_logic > dout_words_V_data_V_1_vld_in;
    sc_signal< sc_logic > dout_words_V_data_V_1_vld_out;
    sc_signal< sc_logic > dout_words_V_data_V_1_ack_in;
    sc_signal< sc_logic > dout_words_V_data_V_1_ack_out;
    sc_signal< sc_logic > dout_words_V_data_V_1_sel_rd;
    sc_signal< sc_logic > dout_words_V_data_V_1_sel;
    sc_signal< sc_lv<2> > dout_words_V_data_V_1_state;
    sc_signal< sc_lv<1> > dout_words_V_last_V_1_data_out;
    sc_signal< sc_logic > dout_words_V_last_V_1_vld_in;
    sc_signal< sc_logic > dout_words_V_last_V_1_vld_out;
    sc_signal< sc_logic > dout_words_V_last_V_1_ack_in;
    sc_signal< sc_logic > dout_words_V_last_V_1_ack_out;
    sc_signal< sc_logic > dout_words_V_last_V_1_sel_rd;
    sc_signal< sc_logic > dout_words_V_last_V_1_sel;
    sc_signal< sc_lv<2> > dout_words_V_last_V_1_state;
    sc_signal< sc_logic > enc_ctrl_V_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > din_words_TDATA_blk_n;
    sc_signal< sc_logic > dout_words_TDATA_blk_n;
    sc_signal< sc_lv<32> > p_Result_2_fu_117_p5;
    sc_signal< bool > ap_block_state1_io;
    sc_signal< sc_lv<32> > p_Result_s_fu_93_p5;
    sc_signal< sc_lv<32> > p_Result_1_fu_105_p5;
    sc_signal< bool > ap_block_state2;
    sc_signal< bool > ap_block_state2_io;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<8> ap_const_lv8_4;
    static const sc_lv<8> ap_const_lv8_10;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_6;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1_io();
    void thread_ap_block_state2();
    void thread_ap_block_state2_io();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_din_words_TDATA();
    void thread_din_words_TDATA_blk_n();
    void thread_din_words_TLAST();
    void thread_din_words_TVALID();
    void thread_din_words_V_data_V_1_ack_in();
    void thread_din_words_V_data_V_1_ack_out();
    void thread_din_words_V_data_V_1_data_out();
    void thread_din_words_V_data_V_1_sel();
    void thread_din_words_V_data_V_1_vld_in();
    void thread_din_words_V_data_V_1_vld_out();
    void thread_din_words_V_last_V_1_ack_in();
    void thread_din_words_V_last_V_1_ack_out();
    void thread_din_words_V_last_V_1_data_out();
    void thread_din_words_V_last_V_1_sel();
    void thread_din_words_V_last_V_1_vld_in();
    void thread_din_words_V_last_V_1_vld_out();
    void thread_dout_words_TDATA();
    void thread_dout_words_TDATA_blk_n();
    void thread_dout_words_TLAST();
    void thread_dout_words_TVALID();
    void thread_dout_words_V_data_V_1_ack_in();
    void thread_dout_words_V_data_V_1_ack_out();
    void thread_dout_words_V_data_V_1_data_out();
    void thread_dout_words_V_data_V_1_sel();
    void thread_dout_words_V_data_V_1_vld_in();
    void thread_dout_words_V_data_V_1_vld_out();
    void thread_dout_words_V_last_V_1_ack_in();
    void thread_dout_words_V_last_V_1_ack_out();
    void thread_dout_words_V_last_V_1_data_out();
    void thread_dout_words_V_last_V_1_sel();
    void thread_dout_words_V_last_V_1_vld_in();
    void thread_dout_words_V_last_V_1_vld_out();
    void thread_enc_ctrl_V_V_1_ack_in();
    void thread_enc_ctrl_V_V_1_ack_out();
    void thread_enc_ctrl_V_V_1_data_out();
    void thread_enc_ctrl_V_V_1_load_A();
    void thread_enc_ctrl_V_V_1_load_B();
    void thread_enc_ctrl_V_V_1_sel();
    void thread_enc_ctrl_V_V_1_state_cmp_full();
    void thread_enc_ctrl_V_V_1_vld_in();
    void thread_enc_ctrl_V_V_1_vld_out();
    void thread_enc_ctrl_V_V_TDATA();
    void thread_enc_ctrl_V_V_TDATA_blk_n();
    void thread_enc_ctrl_V_V_TVALID();
    void thread_p_Result_1_fu_105_p5();
    void thread_p_Result_2_fu_117_p5();
    void thread_p_Result_s_fu_93_p5();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
